name: Brandon Amos
url: http://bamos.github.io
destination: ./_site
twitter: brandondamos
lsi: false
port: 4000
markdown: kramdown
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
permalink: pretty
#paginate: 5
gems:
  - jekyll-sitemap

exclude:
  - .travis.yml
  - validate.rb
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
