name: Brandon Amos
url: http://bamos.github.io
destination: ./_site
lsi: false
port: 4000
highlighter: pygments
markdown: kramdown
kramdown:
  parse_block_html: true
permalink: pretty
paginate: 5
gems:
  - jekyll-sitemap
