name: "Brandon Amos: Blog"
description: The personal blog of Brandon Amos
url: http://bamos.io
destination: ./_site
lsi: false
port: 4000
highlighter: pygments
markdown: kramdown
permalink: pretty
paginate: 5
gems:
  - jekyll-sitemap
